version: '3'

services:
  my_service:
    build:
      context: .
    restart: unless-stopped
    container_name: my_service
    volumes:
      - ./orderbook.db:/usr/src/app/orderbook.db
    # Expose any required ports if needed
    # ports:
    #   - "127.0.0.1:<external_port>:<internal_port>"
    command: python main.py